In [1]:
#1. Створіть одновимірний масив (вектор) із послідовністю чисел, де кожне наступне число більше попереднього на 3, починаючи з 5, та виведіть його значення.

import numpy as np
array = np.arange(5, 100, 3)
print(array)

[ 5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74
 77 80 83 86 89 92 95 98]


In [19]:
#2. Створіть двовимірний масив (матрицю) розміром 3х3, заповніть його добутками квадратів кожного числа та його подвійного значення, починаючи з 1, та виведіть його значення.

import numpy as np
rows, cols = 3, 3
matrix = np.zeros((rows, cols))

for i in range(rows):
    for j in range(cols):
        num = i * cols + j + 1  # Обчислюємо число, починаючи з 1
        square = num ** 2
        double = num * 2
        matrix[i, j] = square * double

print(matrix)

[[   2.   16.   54.]
 [ 128.  250.  432.]
 [ 686. 1024. 1458.]]


In [2]:
#3. Створіть масив розміром 3х3, заповніть його випадковими дійсними числами в діапазоні від -5 до 5 та виведіть його значення.

import numpy as np
matrix = np.random.uniform(-5, 5, (3, 3))
print(matrix)

[[ 1.69312815 -4.17871542 -4.48986047]
 [ 4.32036422  0.13550428  0.43118182]
 [ 2.41003925  2.28394748 -3.57459934]]


In [3]:
#4. Створіть масив розміром 4х4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-рядок, що містить середнє значення елементів кожного стовпця матриці.

import numpy as np
matrix = np.random.rand(4, 4)
column_means = matrix.mean(axis=0)
print("Матриця:\n", matrix)
print("Вектор-рядок:\n", column_means)

Матриця:
 [[0.31822249 0.89480504 0.49324472 0.82790259]
 [0.22662249 0.00209581 0.47073349 0.94792604]
 [0.20563774 0.16786988 0.81507654 0.68993727]
 [0.32045532 0.26388563 0.21346381 0.86758393]]
Вектор-рядок:
 [0.26773451 0.33216409 0.49812964 0.83333746]


In [4]:
#5. Створіть два одновимірних масиви розміром 7, заповніть їх випадковими дійсними числами від -2.5 до 2.5 та виконайте на них поелементні операції додавання, віднімання та множення.

import numpy as np
array1 = np.random.uniform(-2.5, 2.5, 7)
array2 = np.random.uniform(-2.5, 2.5, 7)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Перший масив:", array1)
print("Другий масив:", array2)
print("Додавання:", addition)
print("Віднімання:", subtraction)
print("Множення:", multiplication)

Перший масив: [-1.36418218 -0.60113017  1.58511022 -0.84275866  0.73904683  0.82906985
 -0.5372794 ]
Другий масив: [-2.47636945  0.54745274  2.35042301 -1.92167652  0.99519376 -2.02605815
  2.25722175]
Додавання: [-3.84055163 -0.05367744  3.93553323 -2.76443519  1.73424059 -1.1969883
  1.71994235]
Віднімання: [ 1.11218726 -1.14858291 -0.7653128   1.07891786 -0.25614692  2.855128
 -2.79450115]
Множення: [ 3.37821908 -0.32909036  3.72567953  1.61950954  0.7354948  -1.67974373
 -1.21275874]


In [6]:
#6. Створіть дві матриці 3х3, заповніть їх довільними цілими числами від 1 до 50 та знайдіть їх добуток.

import numpy as np
matrix1 = np.random.randint(1, 51, (3, 3))
matrix2 = np.random.randint(1, 51, (3, 3))

product = np.dot(matrix1, matrix2)

print("Перша матриця:\n", matrix1)
print("Друга матриця:\n", matrix2)
print("Добуток матриць:\n", product)

Перша матриця:
 [[41 22 18]
 [10 48 47]
 [26 44 29]]
Друга матриця:
 [[ 7 10  8]
 [25 38 30]
 [23 33 49]]
Добуток матриць:
 [[1251 1840 1870]
 [2351 3475 3823]
 [1949 2889 2949]]


In [7]:
#7. Створіть дві матриці розміром 4х2 та 2х2, заповніть їх випадковими цілими числами в діапазоні від 1 до 6 та перемножте їх між собою.

import numpy as np
matrix1 = np.random.randint(1, 7, (4, 2))
matrix2 = np.random.randint(1, 7, (2, 2))

product = np.dot(matrix1, matrix2)

print("Перша матриця:\n", matrix1)
print("Друга матриця:\n", matrix2)
print("Добуток матриць:\n", product)

Перша матриця:
 [[5 2]
 [4 1]
 [5 1]
 [3 3]]
Друга матриця:
 [[2 2]
 [3 5]]
Добуток матриць:
 [[16 20]
 [11 13]
 [13 15]
 [15 21]]


In [8]:
#8. Створіть матрицю розміром 2х2, заповніть її випадковими цілими числами в діапазоні від 1 до 12 та знайдіть її обернену матрицю.

import numpy as np
matrix = np.random.randint(1, 13, (2, 2))
print("Матриця:\n", matrix)

determinant = np.linalg.det(matrix)
if determinant == 0:
    print("Оберненої матриці не існує.")
else:
    inverse_matrix = np.linalg.inv(matrix)
    print("Обернена матриця:\n", inverse_matrix)

Матриця:
 [[2 9]
 [5 2]]
Обернена матриця:
 [[-0.04878049  0.2195122 ]
 [ 0.12195122 -0.04878049]]


In [9]:
#9. Створіть матрицю розміром 3х3, заповніть її випадковими цілими числами в діапазоні від 0 до 1 та транспортуйте її.

import numpy as np
matrix = np.random.randint(0, 2, (3, 3))
print("Матриця:\n", matrix)

transposed_matrix = np.transpose(matrix)
print("Транспортована матриця:\n", transposed_matrix)

Матриця:
 [[0 1 0]
 [0 0 0]
 [0 0 0]]
Транспортована матриця:
 [[0 0 0]
 [1 0 0]
 [0 0 0]]


In [10]:
#10. Створіть матрицю розміром 3х4 та вектор розміром 4х1, заповніть матрицю випадковими цілими числами в діапазоні від -5 до 5, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

import numpy as np
matrix = np.random.randint(-5, 6, (3, 4))
vector = np.random.randint(1, 11, (4, 1))

product = np.dot(matrix, vector)

print("Матриця:\n", matrix)
print("Вектор:\n", vector)
print("Добуток матриці на вектор:\n", product)

Матриця:
 [[-4  4  3  1]
 [-1  3  5  5]
 [ 4 -2 -2  3]]
Вектор:
 [[ 3]
 [ 2]
 [ 2]
 [10]]
Добуток матриці на вектор:
 [[12]
 [63]
 [34]]


In [11]:
#11. Створіть матрицю розміром 2х3 та вектор розміром 3х1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

import numpy as np
matrix = np.random.uniform(0, 1, (2, 3))
vector = np.random.randint(1, 11, (3, 1))

product = np.dot(matrix, vector)

print("Матриця:\n", matrix)
print("Вектор:\n", vector)
print("Добуток матриці на вектор:\n", product)

Матриця:
 [[0.98769617 0.7091529  0.43987307]
 [0.52162671 0.73651875 0.50539701]]
Вектор:
 [[2]
 [4]
 [5]]
Добуток матриці на вектор:
 [[7.01136925]
 [6.51631347]]


In [13]:
#12. Створіть дві матриці розміром 8х8, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню суму.

import numpy as np
matrix1 = np.random.randint(1, 11, (8, 8))
matrix2 = np.random.randint(1, 11, (8, 8))

sum_matrix = matrix1 + matrix2

print("Перша матриця:\n", matrix1)
print("Друга матриця:\n", matrix2)
print("Сума матриць:\n", sum_matrix)

Перша матриця:
 [[ 1  3  6  2  5  6  8  8]
 [10  8  8  5 10  1  8  7]
 [ 7  8  2  5  6  3  2  2]
 [ 8  5  2  8 10  8  5  4]
 [ 2  3  4  8  7  7  9  1]
 [ 2  9  2  4  8 10  2  8]
 [10  1  1  5  7  4  6 10]
 [ 2  7  2  8  4  7  1  9]]
Друга матриця:
 [[ 6  5  9  6  4  5  5 10]
 [ 9  3  5 10  6  9  8  3]
 [ 1  2  1  2  5  4  9 10]
 [ 6  8  5  9  2  6  5 10]
 [ 1  8  4  4  2  8  2  4]
 [ 4  4  5  9  3  9  5  2]
 [ 6  6  5  9  8  7  4 10]
 [ 3  2  3  1  8  2  2  2]]
Сума матриць:
 [[ 7  8 15  8  9 11 13 18]
 [19 11 13 15 16 10 16 10]
 [ 8 10  3  7 11  7 11 12]
 [14 13  7 17 12 14 10 14]
 [ 3 11  8 12  9 15 11  5]
 [ 6 13  7 13 11 19  7 10]
 [16  7  6 14 15 11 10 20]
 [ 5  9  5  9 12  9  3 11]]


In [14]:
#13. Створіть дві матриці розміром 8х8, заповніть їх випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть різницю їх елементів.

import numpy as np
matrix1 = np.random.uniform(-1, 1, (8, 8))
matrix2 = np.random.uniform(-1, 1, (8, 8))

difference = matrix1 - matrix2

print("Перша матриця:\n", matrix1)
print("Друга матриця:\n", matrix2)
print("Різниця елементів матриць:\n", difference)

Перша матриця:
 [[ 0.83317829  0.77926283  0.66013261  0.99772134  0.30188693 -0.70485039
  -0.94708903  0.17483535]
 [-0.90990255 -0.35151046  0.56239161 -0.7822366  -0.71274322 -0.76040554
   0.56475389  0.84881925]
 [-0.91191854 -0.44905455  0.13235326 -0.08174831  0.37343105 -0.62650816
  -0.94986729 -0.79837558]
 [ 0.9392301  -0.3116261   0.77329727  0.38428329  0.74079627 -0.90453621
  -0.61409313  0.40495056]
 [ 0.90578567 -0.95222198  0.88394369 -0.90035047 -0.46883349 -0.72185686
  -0.26615493 -0.28258498]
 [-0.11158766 -0.72478454  0.89483569 -0.38997979  0.34187445  0.78438646
  -0.06546391 -0.82375951]
 [-0.03724685  0.79690995  0.80826857  0.88329247 -0.29710325  0.64065964
  -0.34942953  0.30250458]
 [-0.0041151  -0.31114401  0.12518268 -0.89021588  0.28619975  0.53000653
  -0.32867155  0.25979126]]
Друга матриця:
 [[-0.07372501  0.97850374  0.30516644 -0.86781158 -0.0948764   0.07281787
   0.72037564  0.63320256]
 [ 0.78190554  0.43841902  0.975119   -0.52363791  0.56105

In [17]:
#14. Створіть матрицю розміром 5х5, заповніть її випадковими дійсними числами і діапазоні від 0 до 1 та знайдіть середнє арифметичне значення елементів матриці.

import numpy as np
matrix = np.random.uniform(0, 1, (5, 5))

mean_value = np.mean(matrix)

print("Матриця:\n", matrix)
print("Середнє арифметичне значення елементів матриці:", mean_value)

Матриця:
 [[0.71001131 0.2483985  0.61317766 0.1556573  0.51388731]
 [0.13976322 0.59073538 0.17753359 0.51487856 0.61300488]
 [0.82640817 0.6261009  0.75201788 0.47864158 0.25506433]
 [0.87682458 0.24869156 0.92046805 0.58244307 0.5441401 ]
 [0.46120325 0.07619215 0.36616654 0.41380295 0.20835417]]
Середнє арифметичне значення елементів матриці: 0.47654267924523624


In [18]:
#15. Створіть матрицю розміром 9х9, заповніть її випадковими дійсними числами в діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить найбільше за модулем значення елементу у кожному рядку матриці.

import numpy as np
matrix = np.random.uniform(-0.5, 0.5, (9, 9))
max_abs_values = np.max(np.abs(matrix), axis=1)
max_abs_values_column = max_abs_values.reshape(-1, 1)

print("Матриця:\n", matrix)
print("Вектор-стовпчик, що містить найбільше за модулем значення елементу у кожному рядку матриці:\n", max_abs_values_column)

Матриця:
 [[ 0.10233377  0.38432574  0.09158116  0.22051019 -0.12383451 -0.15221889
  -0.2360197   0.4755827   0.19167936]
 [-0.19101646 -0.26655151  0.04871039 -0.32775684  0.34061648 -0.38445604
   0.49069998 -0.18159412  0.38061463]
 [-0.45217829  0.23314956 -0.01544784  0.17685314 -0.38133927 -0.34931181
  -0.49717169  0.4968985   0.13134904]
 [-0.36677566  0.03401643  0.02669695 -0.23863676 -0.17266719  0.3651033
  -0.40893097 -0.0162714  -0.32193469]
 [-0.39577387  0.38230218  0.38085247 -0.19345645  0.19558753 -0.21085392
  -0.3836076   0.13380338 -0.21785551]
 [-0.46680617  0.23029067  0.37214947 -0.29799877  0.39237983 -0.06579639
   0.12990134  0.27524542  0.07771905]
 [ 0.40905163 -0.15012442  0.12499339  0.07500681  0.23951062 -0.37560979
  -0.00777662 -0.31928223 -0.09820288]
 [ 0.13851478  0.24261562  0.49200246 -0.32681303  0.06006228 -0.19551756
   0.12393494  0.14485729 -0.3957532 ]
 [-0.45213499 -0.00649831  0.17325447  0.4830651  -0.27721287 -0.22433772
  -0.25290111

In [ ]:
#Висновок: на цій лабораторній роботі я повторила елементи лінійної алгебри, попрацювала з масивами, матрицями та векторами.
#Посилання на GitHub: https://github.com/nastiadzen/Machine-learning.git